In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

ads = pd.read_csv('ads.csv')
campaigns = pd.read_csv('campaigns.csv')
users = pd.read_csv('users.csv')
events = pd.read_csv('ad_events.csv')

print(ads.shape, campaigns.shape, users.shape, events.shape )

(200, 7) (50, 6) (10000, 7) (400000, 7)

In [8]:
for name, df in [('ads', ads), ('campaigns', campaigns), ('users', users), ('events', events)]:
  print(f"{name}: {df.shape[0]} rows, {df.shape[1]} columns")

ads: 200 rows, 7 columns
campaigns: 50 rows, 6 columns
users: 10000 rows, 7 columns
events: 400000 rows, 7 columns

In [11]:
for name, df in [('ads', ads), ('campaigns', campaigns), ('users', users), ('events', events)]:
  print(f"\n=== {name} ===")
  print(df.dtypes)

=== ads ===
ad_id                int64
campaign_id          int64
ad_platform         object
ad_type             object
target_gender       object
target_age_group    object
target_interests    object
dtype: object

=== campaigns ===
campaign_id        int64
name              object
start_date        object
end_date          object
duration_days      int64
total_budget     float64
dtype: object

=== users ===
user_id        object
user_gender    object
user_age        int64
age_group      object
country        object
location       object
interests      object
dtype: object

=== events ===
event_id        int64
ad_id           int64
user_id        object
timestamp      object
day_of_week    object
time_of_day    object
event_type     object
dtype: object

In [13]:
for name, df in [('ads', ads), ('campaigns', campaigns), ('users', users), ('events', events)]:
  print(f"\n=== {name} - nulls ===")
  print(df.isnull().sum())

=== ads - nulls ===
ad_id               0
campaign_id         0
ad_platform         0
ad_type             0
target_gender       0
target_age_group    0
target_interests    0
dtype: int64

=== campaigns - nulls ===
campaign_id      0
name             0
start_date       0
end_date         0
duration_days    0
total_budget     0
dtype: int64

=== users - nulls ===
user_id        0
user_gender    0
user_age       0
age_group      0
country        0
location       0
interests      0
dtype: int64

=== events - nulls ===
event_id       0
ad_id          0
user_id        0
timestamp      0
day_of_week    0
time_of_day    0
event_type     0
dtype: int64

In [15]:
print("ads")
display(ads.head(3))

print("\ncampaigns")
display(campaigns.head(3))

print("\nusers")
display(users.head(3))

print("\nevents")
display(events.head(3))

ads

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology

campaigns

,campaign_id,name,start_date,end_date,duration_days,total_budget
0,1,Campaign_1_Launch,2025-05-25,2025-07-23,59,24021.32
1,2,Campaign_2_Launch,2025-04-16,2025-07-07,82,79342.41
2,3,Campaign_3_Winter,2025-05-04,2025-06-29,56,14343.25

users

,user_id,user_gender,user_age,age_group,country,location,interests
0,a2474,Female,24,18-24,United Kingdom,New Mariomouth,"fitness, health"
1,141e5,Male,21,18-24,Germany,Danielsfort,"food, fitness, lifestyle"
2,34db0,Male,27,25-34,Australia,Vincentchester,"fashion, news"

events

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type
0,1,197,2359b,2025-07-26 00:19:56,Saturday,Night,Like
1,2,51,f9c67,2025-06-15 08:28:07,Sunday,Morning,Share
2,3,46,5b868,2025-06-27 00:40:02,Friday,Night,Impression

In [21]:
print(events['event_type'].value_counts())
print(f"Total: {len(events):,}")

event_type
Impression    339812
Click          40079
Like           12013
Comment         4108
Purchase        2031
Share           1957
Name: count, dtype: int64
Total: 400,000

In [25]:
print("Platform")
print(ads['ad_platform'].value_counts())

print("\nAd Types")
print(ads['ad_type'].value_counts())

print("Target Gender")
print(ads['target_gender'].value_counts())

print("Target Age")
print(ads['target_age_group'].value_counts())

print("Event day")
print(events['day_of_week'].value_counts())

print("Event Time")
print(events['time_of_day'].value_counts())

Platform
ad_platform
Facebook     127
Instagram     73
Name: count, dtype: int64

Ad Types
ad_type
Stories     64
Image       52
Carousel    51
Video       33
Name: count, dtype: int64
Target Gender
target_gender
Female    83
All       71
Male      46
Name: count, dtype: int64
Target Age
target_age_group
35-44    54
18-24    54
25-34    46
All      46
Name: count, dtype: int64
Event day
day_of_week
Friday       57403
Monday       57250
Thursday     57148
Wednesday    57101
Tuesday      57081
Saturday     57027
Sunday       56990
Name: count, dtype: int64
Event Time
time_of_day
Afternoon    100218
Evening      100002
Morning       99914
Night         99866
Name: count, dtype: int64